trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  acrLoginServer: mycontactmanager.azurecr.io
  imageNameFrontend: contact-frontend
  imageNameBackend: contact-backend
  aksClusterName: contactapp
  aksResourceGroup: dev

steps:
  - task: DockerInstaller@0

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: azure-contact-manager

  - task: NodeTool@0
    displayName: Install Node.js for frontend build
    inputs:
      versionSpec: 18.x

  - script: |
      cd frontend
      npm install
      CI=false npm run build --verbose
    displayName: Pre-test React frontend build

  - task: Docker@2
    displayName: Build backend image
    inputs:
      command: build
      repository: mycontactmanager/mycontactmanager
      Dockerfile: backend/Dockerfile
      tags: |
        $(imageNameBackend)-$(Build.BuildId)
        $(imageNameBackend)-latest
      buildContext: $(Build.SourcesDirectory)/backend

  - task: Docker@2
    displayName: Push backend image to ACR
    inputs:
      command: push
      repository: mycontactmanager/mycontactmanager
      tags: |
        $(imageNameBackend)-$(Build.BuildId)
        $(imageNameBackend)-latest
      containerRegistry: azure-contact-manager

  - task: Docker@2
    displayName: Build frontend image
    inputs:
      command: build
      repository: mycontactmanager/mycontactmanager
      Dockerfile: frontend/Dockerfile
      tags: |
        $(imageNameFrontend)-$(Build.BuildId)
        $(imageNameFrontend)-latest
      buildContext: $(Build.SourcesDirectory)/frontend

  - task: Docker@2
    displayName: Push frontend image
    inputs:
      command: push
      repository: mycontactmanager/mycontactmanager
      tags: |
        $(imageNameFrontend)-$(Build.BuildId)
        $(imageNameFrontend)-latest
      containerRegistry: azure-contact-manager

  - task: PublishPipelineArtifact@1
    displayName: Publish deployment YAMLs
    inputs:
      targetPath: '$(Build.SourcesDirectory)/K8s/Deployment'
      artifactName: 'manifests'
