trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageNameFrontend: contact-frontend
  imageNameBackend: contact-backend

steps:
- task: DockerInstaller@0

- task: Docker@2
  displayName: Build backend image
  inputs:
    command: build
    Dockerfile: backend/Dockerfile
    tags: |
      $(imageNameBackend):$(Build.BuildId)
    buildContext: $(Build.SourcesDirectory)/backend

- task: Docker@2
  displayName: Build frontend image
  inputs:
    command: build
    Dockerfile: frontend/Dockerfile
    tags: |
      $(imageNameFrontend):$(Build.BuildId)
    buildContext: $(Build.SourcesDirectory)/frontend

- task: Docker@2
  displayName: Push backend image to container registry
  inputs:
    command: push
    tags: |
      $(imageNameBackend):$(Build.BuildId)

- task: Docker@2
  displayName: Push frontend image to container registry
  inputs:
    command: push
    tags: |
      $(imageNameFrontend):$(Build.BuildId)
