trigger: none

stages:
  - stage: DeployToAKS
    displayName: Deploy to AKS
    dependsOn: []
    jobs:
      - job: DownloadAndApply
        displayName: Download and Apply release-pipeline.yml
        pool:
          vmImage: ubuntu-latest

        steps:
          # ✅ Download build artifact 'manifests' from previous pipeline
          - download: current
            artifact: manifests
          - download: current
            artifact: release-pipeline    

          # ✅ Install Kubectl
          - task: KubectlInstaller@0
            displayName: Install kubectl
            inputs:
              kubectlVersion: 'latest'

          # ✅ Set Kubernetes context (Azure)
          - task: AzureCLI@2
            displayName: Set AKS context
            inputs:
              azureSubscription: 'Azure subscription 1'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials \
                  --resource-group dev \
                  --name contactapp \
                  --overwrite-existing

          # ✅ Apply Kubernetes Manifests
          - script: |
              kubectl apply -f $(Pipeline.Workspace)/manifests/
            displayName: Apply Kubernetes YAMLs
