apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-backend
  template:
    metadata:
      labels:
        app: contact-backend
    spec:
      containers:
        - name: contact-backend
          image: mycontactmanager.azurecr.io/mycontactmanager/mycontactmanager:contact-backend-latest
          
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017

---
apiVersion: v1
kind: Service
metadata:
  name: contact-backend
spec:
  selector:
    app: contact-backend
  ports:
    - port: 4000
  type: ClusterIP
