apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-frontend
  template:
    metadata:
      labels:
        app: contact-frontend
    spec:
      containers:
        - name: contact-frontend
          image: mycontactmanager.azurecr.io/mycontactmanager:contact-frontend-latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: contact-frontend
spec:
  selector:
    app: contact-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
